apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: "1.8.1"
    helm:
      values: |
        service:
          type: ClusterIP

        backendStore:
          postgres:
            enabled: false
          mysql:
            enabled: false
          mssql:
            enabled: false
          # залишимо sqlite (дефолт)
          defaultSqlitePath: ":memory:"

        artifactRoot:
          s3:
            enabled: false
          gcs:
            enabled: false
          azureBlob:
            enabled: false
          defaultArtifactRoot: "./mlruns"
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
